api:
    entities:
        Oro\Bundle\CallBundle\Entity\Call:
            documentation_resource: '@OroCallBundle/Resources/doc/api/call.md'
            fields:
                direction:
                    exclude: false # override exclude rule from entity.yml
            filters:
                fields:
                    updatedAt: ~ # enable manually because this field is not indexed

        Oro\Bundle\CallBundle\Entity\CallDirection:
            documentation_resource: '@OroCallBundle/Resources/doc/api/call.md'

        Oro\Bundle\CallBundle\Entity\CallStatus:
            documentation_resource: '@OroCallBundle/Resources/doc/api/call.md'
