api:
    entities:
        Oro\Bundle\CallBundle\Entity\Call:
            documentation_resource: '@OroCallBundle/Resources/doc/api/call.md'
            fields:
                direction:
                    exclude: false # override exclude rule from entity.yml
                externalId:
                    property_path: external_id
            filters:
                fields:
                    updatedAt: ~ # enable manually because this field is not indexed
                    externalId:
                        allow_array: true
            actions:
                update_list: true

        Oro\Bundle\CallBundle\Entity\CallDirection:
            documentation_resource: '@OroCallBundle/Resources/doc/api/call.md'

        Oro\Bundle\CallBundle\Entity\CallStatus:
            documentation_resource: '@OroCallBundle/Resources/doc/api/call.md'
