datagrids:
    calls-grid:
        extended_entity_name: 'Oro\Bundle\CallBundle\Entity\Call'
        acl_resource: oro_call_view
        source:
            type: orm
            query:
                select:
                    - call.id
                    - call.subject
                    - CONCAT(call.phoneNumber, '') as phone
                    - call.callDateTime as dateTime
                from:
                    - { table: 'Oro\Bundle\CallBundle\Entity\Call', alias: call }
        columns:
            subject:
                label: oro.call.subject.label
            phone:
                label: oro.call.phone_number.label
                frontend_type: phone
            dateTime:
                label: oro.call.call_date_time.label
                frontend_type: datetime
            contexts:
                label: oro.call.contexts.label
        filters:
            columns:
                subject:
                    type: string
                    data_name: call.subject
                phone:
                    type: string
                    data_name: phone
                dateTime:
                    type: datetime
                    data_name: call.callDateTime
        sorters:
            columns:
                subject:
                    data_name: call.subject
                phone:
                    data_name: phone
                dateTime:
                    data_name: call.callDateTime
            default:
                dateTime: DESC
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_call_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_call_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_call
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_call_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_call_create
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_call_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
        options:
            entityHint: oro.call.entity_plural_label
            export: true
            entity_pagination: true
            contexts:
                enabled: true

    widget-base-calls-grid:
        acl_resource: oro_call_view
        source:
            type: orm
            query:
                select:
                    - call.id
                    - call.subject
                    - CONCAT(call.phoneNumber, '') as phone
                    - call.callDateTime as dateTime
                from:
                    - { table: 'Oro\Bundle\CallBundle\Entity\Call', alias: call }
        columns:
            dateTime:
                label: oro.call.call_date_time.label
                frontend_type: datetime
            subject:
                label: oro.call.subject.label
                type: twig
                template: '@OroCall/Datagrid/Column/subject.html.twig'
                frontend_type: html
            phone:
                label: oro.call.phone_number.label
                frontend_type: phone
        sorters:
            columns:
                subject:
                    data_name: call.subject
                phone:
                    data_name: phone
                dateTime:
                    data_name: call.callDateTime
            default:
                dateTime: DESC
        properties:
            id: ~
        options:
            entityHint: oro.call.entity_plural_label

    widget-simplyfied-calls-grid:
        extends: widget-base-calls-grid
        options:
            toolbarOptions:
                turnOffToolbarRecordsNumber: 10
                addResetAction: false

    widget-calls-grid:
        extends: widget-base-calls-grid
        filters:
            columns:
                subject:
                    type: string
                    data_name: call.subject
                phone:
                    type: string
                    data_name: phone
                dateTime:
                    type: datetime
                    data_name: call.callDateTime

    activity-call-grid:
        extends: widget-base-calls-grid
        filters:
            columns:
                subject:
                    type: string
                    data_name: call.subject
                phone:
                    type: string
                    data_name: phone
                dateTime:
                    type: datetime
                    data_name: call.callDateTime

    dashboard-recent-calls-grid:
        options:
            entityHint: oro.call.entity_plural_label
            toolbarOptions:
                addDatagridSettingsManager: false
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
        acl_resource: oro_call_view
        source:
            type: orm
            query:
                select:
                    - call.id
                    - call.subject
                    - CONCAT(call.phoneNumber, '') as phone
                    - call.callDateTime as dateTime
                    - directionType.name as callDirection
                from:
                    - { table: 'Oro\Bundle\CallBundle\Entity\Call', alias: call }
                join:
                    left:
                        - { join: call.direction, alias: directionType }
        columns:
            callDirection:
                type: twig
                label: ~
                frontend_type: html
                template: '@OroCall/Datagrid/Column/direction.html.twig'
            dateTime:
                label: oro.call.datagrid.date_time
                frontend_type: datetime
            subject:
                type: twig
                label: oro.call.subject.label
                frontend_type: html
                template: '@OroCall/Datagrid/Column/subject.html.twig'
            phone:
                label: oro.call.phone_number.label
                frontend_type: phone
        sorters:
            columns:
                dateTime:
                    data_name: call.callDateTime
            default:
                dateTime: DESC

    call-for-context-grid:
        extended_entity_name: 'Oro\Bundle\CallBundle\Entity\Call'
        acl_resource: oro_call_view
        options:
            entityHint: oro.call.entity_plural_label
            entity_pagination: true
            toolbarOptions:
                pageSize:
                    default_per_page: 10
            routerEnabled: false
        source:
            type: orm
            query:
                select:
                    - call.id
                    - call.subject
                    - CONCAT(call.phoneNumber, '') as phone
                    - call.callDateTime as dateTime
                from:
                    - { table: 'Oro\Bundle\CallBundle\Entity\Call', alias: call }
        columns:
            id:
                label: oro.call.id.label
            subject:
                label: oro.call.subject.label
            phone:
                label: oro.call.phone_number.label
            dateTime:
                label: oro.call.call_date_time.label
                frontend_type: datetime
        filters:
            columns:
                subject:
                    type: string
                    data_name: call.subject
                phone:
                    type: string
                    data_name: phone
                dateTime:
                    type: datetime
                    data_name: call.callDateTime
        sorters:
            columns:
                subject:
                    data_name: call.subject
                phone:
                    data_name: phone
                dateTime:
                    data_name: call.callDateTime
            default:
                dateTime: DESC
