placeholders:
    placeholders:
        phone_actions:
            items:
                oro_phone_action_log_call_button:
                    order: 20

    items:
        oro_log_call_button:
            template: '@@OroCall/Call/activityButton.html.twig'
            acl: oro_call_create
        oro_log_call_link:
            template: '@@OroCall/Call/activityLink.html.twig'
            acl: oro_call_create
        oro_phone_action_log_call_button:
            applicable: "@oro_call.placeholder.log_call.filter->isApplicable($entity$)"
            template: '@@OroCall/Call/action/logCallButton.html.twig'
            acl: oro_call_create
