oro_call_bundle:
    resource: "@OroCallBundle/Controller"
    type:     annotation
    prefix:   /call


#
# OLD REST API ROUTES
#

oro_api_get_calls:
    path: '/api/rest/{version}/calls.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\CallBundle\Controller\Api\Rest\CallController::cgetAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1

oro_api_get_call:
    path: '/api/rest/{version}/calls/{id}.{_format}'
    methods: [GET]
    defaults:
        _controller: 'Oro\Bundle\CallBundle\Controller\Api\Rest\CallController::getAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_put_call:
    path: '/api/rest/{version}/calls/{id}.{_format}'
    methods: [PUT]
    defaults:
        _controller: 'Oro\Bundle\CallBundle\Controller\Api\Rest\CallController::putAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_post_call:
    path: '/api/rest/{version}/calls.{_format}'
    methods: [POST]
    defaults:
        _controller: 'Oro\Bundle\CallBundle\Controller\Api\Rest\CallController::postAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1

oro_api_delete_call:
    path: '/api/rest/{version}/calls/{id}.{_format}'
    methods: [DELETE]
    defaults:
        _controller: 'Oro\Bundle\CallBundle\Controller\Api\Rest\CallController::deleteAction'
        _format: json
        version: latest
    requirements:
        id: \d+
        _format: json|html
        version: latest|v1

oro_api_options_calls:
    path: '/api/rest/{version}/calls.{_format}'
    methods: [OPTIONS]
    defaults:
        _controller: 'Oro\Bundle\CallBundle\Controller\Api\Rest\CallController::optionsAction'
        _format: json
        version: latest
    requirements:
        _format: json|html
        version: latest|v1
